name: cron
on:
  schedule:
    - cron: '* 9 * * *'
jobs:
  audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: audit
